// French département names need a definite article ("les Yvelines", "la
// Sarthe", "le Var") that can't be derived reliably from spelling alone.
const DEPARTMENT_ARTICLES: Record<string, string> = {
  Ain: "l'",
  Aisne: "l'",
  Allier: "l'",
  "Alpes-de-Haute-Provence": "les",
  "Hautes-Alpes": "les",
  "Alpes-Maritimes": "les",
  Ardèche: "l'",
  Ardennes: "les",
  Ariège: "l'",
  Aube: "l'",
  Aude: "l'",
  Aveyron: "l'",
  "Bouches-du-Rhône": "les",
  Calvados: "le",
  Cantal: "le",
  Charente: "la",
  "Charente-Maritime": "la",
  Cher: "le",
  Corrèze: "la",
  "Corse-du-Sud": "la",
  "Haute-Corse": "la",
  "Côte-d'Or": "la",
  "Côtes-d'Armor": "les",
  Creuse: "la",
  Dordogne: "la",
  Doubs: "le",
  Drôme: "la",
  Eure: "l'",
  "Eure-et-Loir": "l'",
  Finistère: "le",
  Gard: "le",
  "Haute-Garonne": "la",
  Gers: "le",
  Gironde: "la",
  Hérault: "l'",
  "Ille-et-Vilaine": "l'",
  Indre: "l'",
  "Indre-et-Loire": "l'",
  Isère: "l'",
  Jura: "le",
  Landes: "les",
  "Loir-et-Cher": "le",
  Loire: "la",
  "Haute-Loire": "la",
  "Loire-Atlantique": "la",
  Loiret: "le",
  Lot: "le",
  "Lot-et-Garonne": "le",
  Lozère: "la",
  "Maine-et-Loire": "le",
  Manche: "la",
  Marne: "la",
  "Haute-Marne": "la",
  Mayenne: "la",
  "Meurthe-et-Moselle": "la",
  Meuse: "la",
  Morbihan: "le",
  Moselle: "la",
  Nièvre: "la",
  Nord: "le",
  Oise: "l'",
  Orne: "l'",
  "Pas-de-Calais": "le",
  "Puy-de-Dôme": "le",
  "Pyrénées-Atlantiques": "les",
  "Hautes-Pyrénées": "les",
  "Pyrénées-Orientales": "les",
  "Bas-Rhin": "le",
  "Haut-Rhin": "le",
  Rhône: "le",
  "Haute-Saône": "la",
  "Saône-et-Loire": "la",
  Sarthe: "la",
  Savoie: "la",
  "Haute-Savoie": "la",
  Paris: "",
  "Seine-Maritime": "la",
  "Seine-et-Marne": "la",
  Yvelines: "les",
  "Deux-Sèvres": "les",
  Somme: "la",
  Tarn: "le",
  "Tarn-et-Garonne": "le",
  Var: "le",
  Vaucluse: "le",
  Vendée: "la",
  Vienne: "la",
  "Haute-Vienne": "la",
  Vosges: "les",
  Yonne: "l'",
  "Territoire de Belfort": "le",
  Essonne: "l'",
  "Hauts-de-Seine": "les",
  "Seine-Saint-Denis": "la",
  "Val-de-Marne": "le",
  "Val-d'Oise": "le",
  Guadeloupe: "la",
  Martinique: "la",
  Guyane: "la",
  "La Réunion": "",
  Mayotte: "",
  Corse: "la",
};

// Adds the definite article for a French département name, e.g. "Sarthe" ->
// "la Sarthe", "Yvelines" -> "les Yvelines". Falls back to the bare name for
// anything not in the table (e.g. Nominatim returning a country/region).
export function withDepartmentArticle(name: string): string {
  const article = DEPARTMENT_ARTICLES[name];
  if (article === undefined) return name;
  if (article === "") return name;
  if (article === "l'") return `l'${name}`;
  return `${article} ${name}`;
}
